import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check, Heart, ShieldCheck } from "lucide-react";
import { Section } from "@/components/ui/section";
import { Button } from "@/components/ui/button";
import { MEMBERSHIP_TIERS } from "@/lib/constants";

export const metadata: Metadata = { title: "Membership — OvercomeHER Circle", description: "Choose the OvercomeHER Circle membership tier that fits the level of support you want right now." };

export default function MembershipPage() {
  return <>
    <section className="bg-warm-50"><div className="mx-auto max-w-7xl px-6 py-20 md:py-28 text-center"><p className="text-sm uppercase tracking-[0.25em] text-plum-400 font-medium">OvercomeHER Circle Membership</p><h1 className="mt-4 text-5xl md:text-6xl font-semibold text-warm-900">Choose the support that <span className="italic text-blush-400">fits now</span></h1><p className="mt-6 max-w-2xl mx-auto text-lg text-warm-500">Three levels of support. One clear starting point. Every tier begins with a 7-day free trial.</p></div></section>
    <Section variant="default" size="lg"><div className="grid md:grid-cols-3 gap-8">{MEMBERSHIP_TIERS.map((tier) => { const savings = Math.round(tier.priceMonthly * 12 - tier.priceYearly); return <div key={tier.id} className={`relative flex flex-col p-8 rounded-3xl ${tier.highlighted ? "bg-warm-800 text-white ring-2 ring-blush-400 shadow-xl" : "bg-white border border-warm-200"}`}>{tier.highlighted && <span className="absolute -top-3 left-1/2 -translate-x-1/2 px-4 py-1 rounded-full bg-blush-400 text-white text-xs uppercase tracking-wider">Most Popular</span>}<h2 className="text-3xl font-semibold">{tier.name}</h2><p className={`mt-2 ${tier.highlighted ? "text-warm-200" : "text-warm-500"}`}>{tier.tagline}</p><div className="mt-6"><p className="text-5xl font-bold">${tier.priceMonthly}<span className="text-base font-normal">/mo</span></p><p className={`mt-2 text-sm ${tier.highlighted ? "text-warm-300" : "text-warm-400"}`}>${tier.priceYearly}/year · save ${savings}</p></div><p className={`mt-5 text-sm leading-relaxed ${tier.highlighted ? "text-warm-200" : "text-warm-500"}`}>{tier.description}</p><ul className="mt-6 space-y-3 flex-1">{tier.features.map((feature) => <li key={feature} className="flex gap-2 text-sm"><Check className="h-4 w-4 mt-0.5 text-sage-400 flex-shrink-0"/>{feature}</li>)}</ul><Link href="/overcomeher/join" className="mt-8"><Button variant={tier.highlighted ? "warm" : "primary"} size="lg" className="w-full">{tier.cta}<ArrowRight className="h-5 w-5"/></Button></Link></div>; })}</div></Section>
    <Section variant="warm" size="lg"><div className="max-w-3xl mx-auto"><div className="text-center"><ShieldCheck className="h-12 w-12 text-sage-500 mx-auto"/><h2 className="mt-4 text-3xl md:text-4xl font-semibold text-warm-900">Try the Circle for 7 days before you&apos;re charged</h2><p className="mt-4 text-warm-500">Stripe securely collects your payment method when you start. If you cancel before the trial ends, your subscription does not begin billing. After the trial, your selected monthly or annual plan renews automatically until canceled.</p></div><div className="mt-10 grid sm:grid-cols-2 gap-4 text-sm text-warm-600"><div className="p-5 rounded-2xl bg-white border border-warm-100"><Heart className="h-5 w-5 text-blush-400"/><p className="mt-2 font-semibold text-warm-800">Cancel anytime</p><p className="mt-1">No long-term contract. Cancellation stops future renewals.</p></div><div className="p-5 rounded-2xl bg-white border border-warm-100"><Check className="h-5 w-5 text-sage-400"/><p className="mt-2 font-semibold text-warm-800">Clear billing</p><p className="mt-1">The price and billing interval you select are shown again at Stripe checkout.</p></div></div><p className="mt-8 text-center text-xs text-warm-400">See the <Link href="/membership-terms" className="underline">Membership Terms</Link> for billing and cancellation details.</p></div></Section>
    <section className="bg-warm-800"><div className="mx-auto max-w-7xl px-6 py-20 text-center"><h2 className="text-4xl md:text-5xl font-semibold text-white">Ready to choose your <span className="italic text-blush-300">seat in the circle</span>?</h2><p className="mt-4 text-warm-300">Create your account, choose monthly or annual billing, and start your 7-day trial.</p><Link href="/overcomeher/join" className="inline-block mt-8"><Button variant="warm" size="lg">Choose My Membership <ArrowRight className="h-5 w-5"/></Button></Link></div></section>
  </>;
}
